<!DOCTYPE html>
<html lang="ru">
<link rel="stylesheet" href="style.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,600;0,700;0,800;1,600;1,700;1,800&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Neucha&display=swap" rel="stylesheet"><link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">


<head>
  <meta charset="utf-8">
  <title>КОЛЮЧКА</title>
  <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
</head>

<body>
  <header>
    <nav>
      <div class="logo"><a href="index.php">
          <div class="nameshop1">
            <div class="nameshop">Колючка</div>
        </a></div>
      </div>
      <button class="accordion">КАКТУСЫ
        <div class="panel">
          <div class="podclass1 podclass">
            <div class="cat">КАКТУСОВЫЕ</div>
            <div class="lorem">Ариокарпус</div>
            <div class="lorem">Астрофитум</div>
            <div class="lorem">Ацтекиум</div>
            <div class="lorem">Эхинокактус</div>
          </div>
          <div class="podclass2 podclass"> <a>
              <div class="cat">ПЕРЕСКОВЫЕ</div>
            </a>
            <div class="lorem">Переския</div>
            <div class="lorem">Барбадосский крыжовник</div>
            <div class="lorem">Переския шиповатая</div>
            <div class="lorem">Переския колючая</div>
          </div>
          <div class="podclass3 podclass"> <a>
              <div class="cat"> ОПУНЦИЕВЫЕ</div>
            </a>
            <div class="lorem">Бразилиопунция</div>
            <div class="lorem">Цилиндропунция</div>
            <div class="lorem">Грузония</div>
            <div class="lorem">Опунция</div>
          </div>
          <div class="podclass4 podclass"> <a>
              <div class="cat">МАУЕНОВЫЕ</div>
            </a>
            <div class="lorem">Мауения</div>
            <div class="lorem">Майхуэния</div>
            <div class="lorem">Майэния</div>
            <div class="lorem">Пёппеги</div>
          </div>
          <div class="panelpic"><img class="panelpic" src="img/solo.jpg"></div>
        </div>
      </button>
      <button class="accordion">СОПУТСТВУЮЩИЕ ТОВАРЫ
        <div class="panel">
          <div class="podclass1 podclass">
            <div class="cat">УДОБРЕНИЯ</div>
            <div class="lorem">Калийные</div>
            <div class="lorem">Фосфатные</div>
            <div class="lorem">Аммонийные</div>
            <div class="lorem">Универсальные</div>
          </div>
          <div class="podclass2 podclass"> 
            <div class="cat">ИНСТРУМЕНТЫ</div>
            <div class="lorem">Грабли</div>
            <div class="lorem">Лопатки</div>
            <div class="lorem">Рыхлители</div>
            <div class="lorem">Перчатки</div>
          </div>
          <div class="podclass3 podclass"> 
            <div class="cat">ЛАМПЫ</div>
            <div class="lorem">Дневные</div>
            <div class="lorem">Ночные</div>
            <div class="lorem">Круглосуточные</div>
            <div class="lorem">Ультрафиолетовые</div>
          </div>
          <div class="podclass4 podclass">
            <div class="cat">ПОД ЗАКАЗ</div>
            <div class="lorem">Удобрения</div>
            <div class="lorem">Инструменты</div>
            <div class="lorem">Лампы</div>
            <div class="lorem">Гибриды</div>
          </div>
          <div class="panelpic"><img class="panelpic" src="img/kit.webp"></div>
        </div>
        </div>
      </button>
      <button class="accordion">ЗЕМЛЯ
        <div class="panel">
          <div class="podclass1 podclass">
            <div class="cat">ПЕСЧАНАЯ</div>
            <div class="lorem">"Сахара"</div>
            <div class="lorem">"Гоби"</div>
            <div class="lorem">"Виктория"</div>
            <div class="lorem">"Невада"</div>
          </div>
          <div class="podclass2 podclass"> <a>
              <div class="cat">ЛЕСНАЯ</div>
            </a>
            <div class="lorem">"Тропик"</div>
            <div class="lorem">"Тут был текст"</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="podclass3 podclass"> <a>
              <div class="cat">СТЕПНАЯ</div>
            </a>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="podclass4 podclass"> <a>
              <div class="cat">МИКС</div>
            </a>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="panelpic"><img class="panelpic" src="img/soi.jpg"></div>
        </div>
      </button>
      <button class="accordion">ГОРШКИ
        <div class="panel">
          <div class="podclass1 podclass">
            <div class="cat">ИЗ ГЛИНЫ</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="podclass2 podclass"> <a>
              <div class="cat">ИЗ ДЕРЕВА</div>
            </a>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="podclass3 podclass"> <a>
              <div class="cat">ИЗ КАМНЯ</div>
            </a>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="podclass4 podclass"> <a>
              <div class="cat">ИЗ СТАРЫХ ГОРШКОВ</div>
            </a>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
            <div class="lorem">Тут был текст</div>
          </div>
          <div class="panelpic"><img class="panelpic" src="img/kit.webp"></div>
        </div>
      </button>
    </nav>
    <div class="name_slaider"></div>
    <!-- Slideshow container -->
    <div class="slideshow-container">
      <?php require("catalog_db.php");
      $products = get_products();
      require("slaider.php") ?>
      <!-- Next and previous buttons -->
      <a class="prev knopkee" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next knopkee" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>
    <!-- The dots/circles -->
    <div style="text-align:center" class="dots">
      <?php require("slaider123.php") ?>
    </div>
  </header>
  <main>

    <div class="tovar"><?php require("slaid.php") ?></div>
    <DIV class="osnova">
      <div class="novo">НОВОСТИ
        <div class="news">
          <div class="ima">Куда надо ставить кактус?</div><img class="img_news" src="img/pod.jpg">
          <div class="text_news">Первое, о чем следует позаботиться, — это выбор места для содержания кактусов.
            Эти растения необходимо размещать на южных, юго-восточных или юго-западных окнах,
            так как потребность в солнечном свете у большинства кактусов огромная.
            Свет для них является главным фактором роста.
          </div>
        </div>
        <div class="news">
          <div class="ima">Как поливать того кто поливает себя сам.</div><img class="img_news" src="img/rosa.jpg">
          <div class="text_news">Большинство пустынных кактусов даже в самую жаркую погоду не требует много воды.
            Летом их поливают в среднем 3-4 раза в месяц, зимой не поливают совсем. </div>
        </div>
        <div class="news">
          <div class="ima">Люди косо смотрят на кактус у монитора?</div><img class="img_news" src="img/gik.jpg">
          <div class="text_news">
            Известно, что электромагнитные излучения,
            исходящие от прибора, вредны для здоровья. Чтобы их нейтрализовать, рекомендуют ставить кактус возле компьютера,
            якобы он способен их поглотить.</div>
        </div>
      </DIV>

      <form method="post" id="forma" action="botscript.php">
        <div class="forma">
          <img class="mail" src="img/mail.png">
          <div class="mailTitle">ЗАКАЗАТЬ КАКТУС</div>
          <div class="kus">
            <div class="name">Ваше имя:</div>
            <input type="text" name="name" placeholder="" size="40">
          </div>
          <div class="kus">
            <div class="tel">Ваш номер:</div>
            <input name="tel" id="phone-mask" placeholder="+7 (000) 000-00-00" type="tel" size="40">
          </div>
          <div class="kus">
            <div class="email">Ваш ящик:</div>
            <input name="mail" placeholder="@email" type="text" size="40">
          </div>
          <div class="kus">
            <div class="zakaz">Ваш заказ:</div>
            <textarea class="comment" placeholder="" name="comment"></textarea>
          </div>
          <div class="but"><input class="but2" type="submit" value="ОТПРАВИТЬ">
            <input class="but2" type="reset" value="ОЧИСТИТЬ">
          </div>
        </div>
      </form>
      <section class="info">
        <div class="onas" id="onas">
          <div class="zagcel">НАШИ ЦЕЛИ:</div>
          <div class="cel">-ПОДОБРАТЬ ВАМ ИДЕАЛЬНЫЙ КАКТУС,</div>
          <div class="cel">-РАССКАЗАТЬ КАК ЗАОБИТЬСЯ О НИХ,</div>
          <div class="cel">-СНАБДИТЬ ВАС ВСЕМ НЕОБХОДИМЫМ.</div>
        </div>
        <div class="konta">
          <div class="zagkontakt">КОНТАКТЫ:</div>
          <div class="kontakt">Москва Ул. Ленина д.60.</div>
          <div class="kontakt">Санкт-Петербург Ул. Ленина д.50.</div>
          <div class="kontakt">+7(777)777-77-77</div>
          <div class="icon">
            <img class="ipic" src="img/inst.png">
            <img class="ipic" src="img/vk.png">
            <img class="ipic" src="img/telega.png">
            <img class="ipic" src="img/dis.png">
          </div>
        </div>


      </section>
  </main>
  <footer>
    <div class="copy">© Александр Мурашев 2021</div>
  </footer>
  <script src="slaider.js"></script>
  <script src="knopke.js"></script>
  <script src="add.js"></script>
  <script src="https://unpkg.com/imask"></script>
  <script>
    let phoneMask = IMask(
      document.getElementById('phone-mask'), {
        mask: '+{7}(000)000-00-00'
      });
  </script>
</body>